#!/bin/bash

NAME="{{ project }}"
DJANGODIR=/var/www/{{ project }}
USER={{ project }}
GROUP=webapps
NUM_WORKERS=`expr 2 \* \`cat /proc/cpuinfo | grep processor | wc -l\` + 1`
DJANGO_WSGI_MODULE={{ project }}.wsgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment.
cd $DJANGODIR
source .venv/bin/activate

export DJANGO_SETTINGS_MODULE={{ project }}.settings.{{ settings }}

# Programs meant to be run under supervisor should not daemonize themselves
# (do not use --daemon).
exec .venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
 		--name $NAME \
  		--workers $NUM_WORKERS \
  		--user=$USER --group=$GROUP \
  		--log-level=info \
  		--bind=127.0.0.1:2000
